### ISSUE TITLE
followed instructions for the online replit program but it throws errors.

### ISSUE THREAD

**Issue by dosuserx** [tra38/Paranoia_Super_Mission_Generator#15]
this is all it outputs. no prompt for name, no http address. i tried bundle install, but still throws errors when i "ruby main.rb".

Traceback (most recent call last):
    16: from main.rb:49:in `<main>'
    15: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/inline.rb:54:in `gemfile'
    14: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/settings.rb:115:in `temporary'
    13: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/inline.rb:61:in `block in gemfile'
    12: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/settings.rb:115:in `temporary'
    11: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/inline.rb:62:in `block (2 levels) in gemfile'
    10: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/installer.rb:24:in `install'
     9: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/installer.rb:72:in `run'
     8: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/process_lock.rb:9:in `lock'
     7: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/process_lock.rb:9:in `open'
     6: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/process_lock.rb:12:in `block in lock'
     5: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/installer.rb:90:in `block in run'
     4: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/installer.rb:208:in `install'
     3: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/installer.rb:268:in `install_in_parallel'
     2: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/installer/parallel_installer.rb:78:in `call'
     1: from /var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/installer/parallel_installer.rb:102:in `call'
/var/lib/gems/2.5.0/gems/bundler-2.2.7/lib/bundler/installer/parallel_installer.rb:197:in `handle_error': Bundler::GenericSystemCallError: There was an error accessing `/var/lib/gems/2.5.0/cache/calyx-0.22.0.gem`. (Bundler::InstallError)
The underlying system error is Errno::EROFS: Read-only file system @ rb_sysopen - /var/lib/gems/2.5.0/cache/calyx-0.22.0.gem
An error occurred while installing calyx (0.22.0), and Bundler cannot continue.
Make sure that `gem install calyx -v '0.22.0' --source 'http://rubygems.org/'` succeeds before bundling.

In Gemfile:
  calyx

Bundler::GenericSystemCallError: There was an error accessing `/var/lib/gems/2.5.0/cache/progressbar-1.11.0.gem`.
The underlying system error is Errno::EROFS: Read-only file system @ rb_sysopen - /var/lib/gems/2.5.0/cache/progressbar-1.11.0.gem
An error occurred while installing progressbar (1.11.0), and Bundler cannot continue.
Make sure that `gem install progressbar -v '1.11.0' --source 'http://rubygems.org/'` succeeds before bundling.

In Gemfile:
  progressbar

Bundler::GenericSystemCallError: There was an error accessing `/var/lib/gems/2.5.0/cache/redcarpet-3.5.1.gem`.
The underlying system error is Errno::EROFS: Read-only file system @ rb_sysopen - /var/lib/gems/2.5.0/cache/redcarpet-3.5.1.gem
An error occurred while installing redcarpet (3.5.1), and Bundler cannot continue.
Make sure that `gem install redcarpet -v '3.5.1' --source 'http://rubygems.org/'` succeeds before bundling.

In Gemfile:
  redcarpet

**Comment by tra38** [comment]
Oh dear, thanks for letting me know. I'll see what I can do to fix this, and I'll keep you posted. Sorry for not reading this sooner.

**Comment by tra38** [comment]
@dosuserx, I manage to identify the issue and fixed it. I was able to run the application as a guest, get a prompt for a name, and generate a [hyperlink to the generated mission](https://itty.bitty.site/#/?XQAAgACJLwAAAAAAAAAeHAPDwmL05FB6dgDSpNuhvgF5dUWJ36ktDDm6MPucb7i2e8IKk8iGVdUAzj2t1ogZFAAPCUSf5/jF648gS6FO+5MS8PiDnJpOU6/dejmHQ1ljVLxQRCgio/xJdaHQCxnvujo/o9EHvKn9DliYSL46NMTm9dy3TtCfI2QUUsbSrOAQ33nEIomtvDDROoi5Exc20JZA5HPKKwLhbYBuDvYb/yGP1HWC6mbOVoxJ7fqkJSwFCVkNTLqXczVzhYw172VETV1imzgo+4i8UMuVtqSWNh3p2KaGXU8sXGqFZvm4HhNDSFvMWV3go8urFtvVFRRVjkuvGQuxhjpztDKNYgK10hLTxCOXc2qcvK43NGHw4m9c8B4c6HHyFzr1ntuMKKtRCc9h4stcuEEO218KZhrlx3x0IAC9G/5ncAPWI+/vwJeH4SEnrbGHfkehu00wW2JTCQ5TIoAZsGkVtXYiHuTZiflxjTiGfFqW1T2pTfuwIy6cnYkokE0OyMulx747X8SlPc1CWt2usOWht619JvQ0L9W5oBycM2q5qdt2QyTQuXBBZYGyqvXcy1/6Zpgrl3Ix7oR6VgVShVVQ9V62SeLAoZj7AzwONavg1NFj6hlFqmctmsK5VZ/Xdr1M3LH9uswG2nKnQzMuwl+xvnoBGmMXH6j/EqirewG0kzqM1jQ5AoBqW9FqiVAlvjGpXqiPuKmjqdo0TBl/3MiqgKiS4fd6O9S+m5aSXicdvVs2dlGePgF9N+dsVjjuJNogta8CyvdqhPR/+A2CODewjC5FR3sdeWUvifcoyUSyxGYmuFFGjoz/hNsYH8B4IhyXVmAClNQvlp/rFP/2Y+cmcrN0F3K3pQH5RopH7zYuvYH1Lnt/LfTuAsAH71CAHYjeI72hS4UzoTjmFmY8kabGKiooI30/LH8l4ZZ9tEhcR7n1B+wDZpCIH0xc653iUF0X8w8tS6og/TfmcrFAMdwVuz8biE7mEWj7shnzgMiA8xynmjVg13darbwz83b1msRJ5N49DXsRhqiDwMqZ1icRgVR1RlJf5QF7Vzd57Hk+WdtHpxlE37AlIXaSc0CS3v0tjjO1hxP1mMP7v6O519dBZBhzjeVdOx0jK05Um1590+gudbK2g9Mq06tawqiMqtP6ZUxaWu88vNFz/pORffxtwYTDRaoj3uz+0QFxplDE7qx4tpJyUinKrgwTGyGdiitjc1wDyfxM6O4jP2Xtl4CVjmzjnt02O92LOY+yfBbLL/MKQyZpfg4VZ6siRhhR4zxSxxHDLo3FpJYI6ZSgvckqdQgyKKTOXKuquNRFUj11QA3UXIKZhKyGeZDAK+1pk6N15OXktxOtqUbHmt3/3oXcT5b/0Eif+YSmbssQpve6pU7/YEPAMjlmJ3j8lo9i7dcAjMZwbRjFPqZsWUaCPhSRrAFNyKuVpNziJlqAnMyaY/4gU91HyW2sFpfQCbZdckTqRKl6+JWS9m3z9TuhavcoQKEcqjCnYGaoXVYRTX5Alt3shHHKGdYelN/F3jmJIlPMJ6YBgD987R1WilkmQXqIeibF2d/t0UrMBuKB3d8pMqQfBno5gAFbWllF0MCiifK/UcU46aGiJZa9A03bqGqrLbugwDmgHoqv9XVtA55HwhFb4ZdeSBfHVpcm522K9Yqsnb1DWAiQJV6jCIwdVLaXwWwjfarA70ROalS5HMIj4rAIZ66+U+DETQRbKct9mXnCSy5e6yivLeEdAbxFbFteyu0ck71yYItwVUXH2UnWe2BBMuihdapHFLUZ4zoMgfPoROD06Ix2i/gNYJXS2UVuJuZdIJYbMwZyYdymvzX8gVSXfR6h/o0nM3ayeUsXlkzjT580vQkxdlZC19xyK4R1jR720Q0LJQZSyV0HbHKtHjOr2FdXFD823Ld9zNMr9vJG/IA7WpeYVDZz9xyyLNOQQMPrVtEO7uAVEcRx6GwqoiWXK5mKsKX/ZuKx9bpFvCZo4fpIhjqL+16P0LK08/9Bu2dz2uMFrqd9dr2pwkMNa1ZaUzffeKdxMz36uxKO/1CVjg64tcHYjLhM8tcGrJpwzYWGRhRJUxjO4KCR21dfLha54EbYhjQ+D3jgiks312wEdflgnIea/QfOb0Fu3s1sfho2Sgasaq0+VSEWpVEJxAdHcbdnT37ymv9kLlarpgilhKNHvovqxwRIUeu9T4GjMrFFh7WoiV7nry75G9B6Nvs0ID/LzrR8cXVhb4VuOyaXslZVTEMGDT+LS0m85lnMCTNFN6uzCrk4IVzR0FkyMxveYLk+7eIFbDz3AZnNBMwG3P0VsbNRW/nZ5/Zj7nU3+E6Z5n7V/ex2P0lYMEk9q5EO1wbbjadz/r/GqE7Rnb/67k/idb56oz/Way0bvAP4iNqOMapPMyBVqQiwbyEQW3XrVFE896r5xbkUK7AmRS7axIjyMTYWbd+6NrdEzov5YbJwZmBOecCvuEFH4IYZjGELRyfE9eqioSiImHjUf3QjtYyXud8gzndjtSgjPNG5wF3KWERwvimxpSOQJmEHXycmeRI4TB/d5KYh1mpzoCknrOCqLl+gvUh/sIsr0myW7VGUsWbuAM1Pb2KSDAk8ZQ/IDQZfvmtlvkKstLuS8hVdX+X0Gme52kzm5qiHzudKqZhYPvs+eVCRkdArxNFkgDWYJPaN/SZkHDuIJlA2NeKDHRpNaeID5tf+xWL1LjV+iaUdBCFO/85NXWBKBzQX8zE3WxJTuMSiqn5Pto2Wwz7nj517/W5yXXQSJikLU5pywkWprcC/+FbdFQS+myj8paoy2Q1rLOhLxmTJPND3yH5gsIAFAc+KHN2buC64MjDWKeIo6hNwsqst/2j0KOtCPtx51Z1QE8KMLD4/2z4Eq3hpXKJ1d63oV5xzLbquu2IShIkrLiv0d3eWYSc6Qmwf4ccWILosML6Z4154XyOQW6cqt+TCAx1Qfv5b4m+pSjobwHzoKiKKoP5C/hrglPQX2rmpGdfKBOcvepGJG0KlpH0QdPhmAv82eEBdHPDLtM0x7LSWAZDMMuvfIxrVj7nXq4h+OSsyk/ZY/73IYXhpBQLRL3wqLJ8HSRVYYv8f8LID3VwHzkJpz3iuMr89mdVjHC8htMjKBNo3sANH3LpMPDUUSlcTVGJWd57WMiFQHeI8nj/NLgO1KrKHC2JnwSgzBe6EkkPnySvX7dK3ezrGsP95pvfeHju/BrhL7ALXwaQ7wGqy08nD2XCEj7fMpGqKzCydH+sbYpDwnUEu4HkAlXwPA53KC6fZhEHE8pcYN1IaCgnqnTZHBUE/mZdzTAaL/+k6Dnwebny08VcomjomXN4Cm1+k5QCJV+6qDsZvRDv0klJjLrl85GzeULp/6tROjdUhzw67uRq66IWUYdtSWn1Jj9n3XxuE7zK2IYh0aWMfWSZaVAUkFiUdf926Az3DjavPBJI8S7llOrDHti3/uCgv8CyjmGSF0o2qyaMkzPCFitEh+5/r919QNGq3TOeb56B/j87ek3XlyKRktK6EVnQL/jWUFqVwXI+76iLh8HxNJ3IGq1l4W0Ublul5D/29ThIfw5P0a1dvmrD0CRS3Cndj4DpMTJxgitwzbmRWvty0noJUzQZs9i69EZ2hPESwWcOVZewsZrvzNhTUOEb+/ian5l3YKQox6Cw0W+vblHLvMqqoViaxfk6kCzsB9uCZ5to6YYEmFsBFxobmdRN8eNNpBawSJHNPm+YTTYhwWfbxMWjfNutwoQ0VmZ7ToRPloJZQ9y2aQ0oEec/Fi1tLeZEl81jlU+gEebP8nkHA7hI0sY2Zm69u6EaBh+Xz2nvIklXG+yCYp+nevwAK4gU6o5i6BkG4CsJ+5O/VDeobeoBn+W0pwdZRYtXLJhFmZW2A/9ntfoW7UokYVG16keOZbHEdOwEIcVZiYJUWun2mDxYFg2KUoqgDUfxYw6qjAu3vM52Ehl0By4pJwzhDSA08awlEGomWG5IbWiROL7Hp6X/wBEwRfzrfnrF6cJgICDlJTrjPNJE9s91yoqUPM78VCZ8e7cWRYLE3RmWwUe1kUS2OogFhZp8k7pYCZwrCBLUHMTBAKn0hlpXdefvixDw2l5dAaqC8Qnfq45H3tGOoHaMhYEBp8Modi9KM6qh95kZhKzZdp3sZ62MwdlCTPYpHnrfqIMY78bxnl+Y0TkuwMsF+gTItnVFtDT3zlK1f/dcqM3FUz5U5lM/0P1fCai1lWn7+uW2Clb/uaDRgDGnEf8Ya/7BZlvv+kKBY1TGAz+0TGhvyQqVilVTPb2s0fUV2P63xUdAEswPbFm5+DWRpS2ho8enkj8G7V12zM992u8gYepFxe2X8xlnr+rpAVBUbx6rQG9HsWAJ5ZMZeEBWEE7rtPyoEIDFbtLEOLeaMd/slUJfXjbT501EjHykBQ3U457n9wfBGznc6ywP2sOsBEMJsvvWZWDWbymhFLx6DzUu/P8sL6huZC46f7IsySqok7OLZ+uokbB4NDPssdgXsLlazWmy0EYKUtNTNqUZpp4P9PMwon+NU06R+4/a26BZIq9DBpuNTGvHzzHD1t7A4dcDogT8b1TdJJVksnvI9pB2spLGlvNw+qnN7tpiFHAEIE6xvRcV4Ey/O0928eXxNU8UUUGEo5RK2ap+UtHMLGFdvGe+Op6KMZuOajy2WoZRMgoPX7HXta4Dd79mNvzObZQ0LrAOibKI2Mt9yOaITQgXBw5TfT8mTJC11n+hUSNtFoOhijnuxj+N1D2ma6vEKQXlCZ7bs/0WV0Q5n43zPGCLkTYLDJq64ZxkuD478HeSCw1hDFmSh4u02LjZZNiBFp/ChEWlzusBXvrgJYjkBbB7vNI2BUg12LVJ/ki8gVeIZBRRjOaWr0cNaop3cjYM5wCNRHILZN2g7jPMOfkJhW5yTzbm3m7PMqvLnLrZ8ui/GPIoiGgxccC/6LZCaq4LDpXuInSGLn8B3Mja1DY4lMZSOn5RJTINLIIsBusCPRYFZO3NLZboKwQ6Tbj5JpQ4O4sGmi8nepGfGfam9GuDUhZQ+ke3K/X85Zbdwhjg1skPjRSQG3P3a7sD0E+MjLkPE96yb3MufUF+QcnPVnrWX/dkB5bZLdIv75UTQbWxlX4vNOymN6VfKURq2pV49v/bfYdmpp3L2eooEK7qTkq7HvFOYE06pdtdcMg44RtXQ66CArh3YCRc5PhG0wjhIrctZm6KiEP3fulMzTv1UlKVipGCfDNIjJjYDTtPs9Mn1ntidKuZdb8JrVy++otW9KnxLVQGT+ukdwAlxbloe4Q6cmrsFFMy5vXDvCRM3rvHTBFt85KH8Ovq+uM9o/wZ3pIZaK1I8vsOAtPa8e7TvnHh9WM3nPQSixaRAuk52SjT3geW1dFvqu9UA2/bkpBqQUNRwD5I9XOj/SAOVFEXqz5qz0ugxRyFYD0UeE3ixybjRPLBq4D1dENALBQAAIDNwe+6y41KhurwWerVWIGQu/A3JuWNObBUjkggXh4o6Zuu1USUEEJDWfHAPKlTlNZ+W1XhqvCkhHYa02TXYeITSUC+Q/IXNirt21m1eYlwzgBrd7EsVM64Qo7I7/qceVa+ZxYdpqrQ0PPQfZ74VFluER6WIpgBMUwrzD5CpMOrZ5o2rXnTLXP7FwUxOI0qgUmkPUxQBQifmy0tnpn7EN+iTvXOFnTGGOrvuuyKbpFaCxm+SregmHyLJW/oQgXvvzXzGgEXrSVX5GsmCbfLfrIDaOsqtkelzsxloej6SAg+FyWAlscSCXB4mXW0Edi+nrhFY3qV7hqf0w76Vq4+y2IXT5qeiU7CVTMg1auBDE+wynbdu4DiCLZenBwO7Y2PdxrCGMC6C941SK3dtcpWJGt2CTWuBvzuNtkAcb0dGMnKVESuv5qqupm4x5leonDWLDB61ivaiUfT/rPMnwhety3jrPtsnDt2FvLJVjOQDGwrsRVrQYfcS+w97YqRpcKh7qEYGA2IplUesLR7Z47BObFLfQDT5xBudP5syR5r/CEOkzI10X4aGsoNrQ85USr8zTisobCvz8ph3nQu6AC1y7sTw06J6gOuTPO2YU+3knEpgM4oI/5Gkuo7uoQGfAwiYRQewAZFy+9l2BJhWSiRIg6VdgVA9jO+P4JDI0LpjGg4nxx3PYHH4O5zraT7Ir6j+L1LvmsYXkFcPKGYm6BQvKzpNAeIhKO10nnewneXrdL+GFH0II1BypnZtpNvmbgso2ZObYmmKxuiHByhOV3w/NsWHJlc+krCLsbkQ5PifstYfAOfxGKFWfY11u9TBJwe+0vta7a4CW6x9x5CaREIA58ikG0A6ByN0gveRpsFzddEmbc17N9Bw1BNs2v5p1RHXWVzN2RANWhIX6IIeWJ/FU1YJLFtO+T+Wl1vdHwty8nfDyYA68w7ykfKgNJAQD2uTQtYQxhLEFPZSBlmTcwk4zXmlNCiCxzGcz4U3gzC82zORcBmSehtB+Pme++I4oHKBhalR+CfFR//fFqV4VSSXRPkc8dh9UZR8+e6+DS/OsVM0WfpuGcjQODFLQpzMWiYm+Sxf9jbHriZjGBSUUSZjlye1ms5dTvIvHHd8c9ibZrcqu8Rp82cWsO9ks78Syqj1p0VJeGRIhxq0AA==). Let me know how it works on your end. I hope this resolve your issue, even though it may not have been prompt. Better late than never, I suppose.

**Comment by dosuserx** [comment]
thank you so much. it works perfectly now. its also as if you knew that my
friend suggested me running paranoia 3 days ago. it looks great, works
great. i really appreciate it.

**Comment by tra38** [comment]
@dosuserx, You're welcome. Good luck with your next PARANOIA session!
